# Generated by Django 5.2 on 2025-04-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio en oferta')),
                ('fecha_fin_oferta', models.DateTimeField(blank=True, null=True, verbose_name='Fin de oferta')),
                ('imagen', models.ImageField(upload_to='media/productos/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('productos', models.ManyToManyField(to='tienda.producto')),
            ],
        ),
    ]
