# Generated by Django 5.2 on 2025-04-11 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoria_alter_segmento_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria'),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='productos',
            field=models.ManyToManyField(to='tienda.producto'),
        ),
    ]
