# Generated by Django 5.2 on 2025-04-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_categoria_alter_segmento_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmento',
            name='productos',
        ),
    ]
