# Generated by Django 5.2 on 2025-04-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_segmento_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='categoria', to='tienda.producto'),
        ),
        migrations.AddField(
            model_name='segmento',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='segmento', to='tienda.producto'),
        ),
    ]
