# Generated by Django 5.2 on 2025-08-14 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_remove_pedido_nombre_cliente_pedido_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('cantidad_por_paquete', models.PositiveIntegerField(blank=True, null=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='tienda.producto')),
            ],
        ),
    ]
